ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

#[rule.add-constant]
#[rule.argument-limit]
[rule.atomic]
#[rule.banned-characters]
#[rule.bare-return]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
#[rule.confusing-naming]
#[rule.confusing-results]
[rule.cognitive-complexity]
  arguments = [15]
#[rule.comment-spacings] wanted but not supported by @latest
[rule.constant-logical-expr]
[rule.context-as-argument]
[rule.context-keys-type]
#[rule.cyclomatic]
[rule.datarace]
[rule.deep-exit]
[rule.defer]
[rule.dot-imports]
[rule.duplicated-imports]
[rule.early-return]
[rule.empty-block]
[rule.empty-lines]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.exported]
#[rule.file-header]
#[rule.flag-parameter]
#[rule.function-result-limit]
#[rule.function-length]
#[rule.get-return]
[rule.identical-branches]
[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.imports-blacklist]
[rule.import-shadowing]
#[rule.line-length-limit]
#[rule.max-public-structs]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.nested-structs]
[rule.optimize-operands-order]
[rule.package-comments]
  Disabled = true
[rule.range]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.string-of-int]
[rule.struct-tag]
[rule.string-format]
[rule.superfluous-else]
[rule.time-naming]
[rule.unconditional-recursion]
[rule.unexported-naming]
[rule.unexported-return]
[rule.unhandled-error]
  arguments =["fmt.Print", "fmt.Printf", "fmt.Println"]
[rule.unnecessary-stmt]
[rule.unreachable-code]
[rule.unused-parameter]
#[rule.unused-receiver]
[rule.useless-break]
[rule.use-any]
[rule.var-naming]
[rule.var-declaration]
[rule.waitgroup-by-value]
