# port of the http server
port: 9480 
# port of the https server
sslport: 9443
# if you use microvault as ca service
ca:
    useca: false
    url: https://127.0.0.1:9543
    accesskey: 3fa6a4bd-74cb-42ff-be40-e5213f8e9b18
    secret: 7d122aab1d57b0177da31829ac791587

# this is the servicURL from outside
serviceURL: https://127.0.0.1:9443
#sercret file for storing usernames and passwords
secretfile: configs/secret.yaml
# true to activate the usage of a apikey (normaly as http header)
apikey: false
logging:
    level: debug
    filename: "${logfile}"
    gelf-url: 127.0.0.1
    gelf-port: 12201

healthcheck:
    period: 30

opentracing:
#    host: "127.0.0.1:5776"
#    endpoint: "http://127.0.0.1:14268/api/traces"^

metrics:
  enable: true