// Package api GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package api

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config": {
            "get": {
                "security": [
                    {
                        "api_key": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Get a store for a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response with config as json",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/apiv1.ConfigDescription"
                            }
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "api_key": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Create a new store for a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Add store",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "tenant",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "api_key": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Delete a store for a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/config/size": {
            "get": {
                "security": [
                    {
                        "api_key": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Get size of a store for a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "size",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiv1.ConfigDescription": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "integer"
                },
                "storeid": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                }
            }
        },
        "serror.Serr": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "api_key": {
            "type": "apiKey",
            "name": "apikey",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "GoMicro service API",
	Description: "The GoMicro service is a template for microservices written in go.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v any) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v any) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
